
lang: en-US
title: Basically Basic
email: dugan.nash@mailinator.com
description: "Your new default Jekyll theme"
baseurl: "/example"  # the subpath of your site, e.g. /blog
url: ""  # the base hostname & protocol for your site, e.g. http://example.com
author:
  name: Rother League
  twitter: rotherleague
  picture: https://api.adorable.io/avatars/285/johndoe.png
twitter_username: rotherleague
github_username: rotherleague
logo: /assets/icons/rotherleague.svg
search: true
search_full_content: true
markdown: kramdown
theme: jekyll-theme-basically-basic
permalink: /blog/:year/:month/:day/:title
plugins: # previously gems
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
feed:
  path: atom.xml
# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Google Analytics
google_analytics: UA—XXXXXXXX-X
